### ISSUE TITLE
登入功能

### ISSUE THREAD

**Issue by a5kgly** [kirbyloco/gamer_autosignin#2]
不好意思，我想部署自動登入的程式碼至google cloud platform的服務Cloud Functions，但是不知道為什麼在google平台上測試函式，都發生錯誤，感謝耀風。

**Comment by kirbyloco** [comment]
目前都是正常使用的。

**Comment by kirbyloco** [comment]
如果是serverless的話，
可能要先確定相關的套件有沒有安裝。

PS. 盡量用留言的方式更新進度，
修改的不會主動通知。

**Comment by a5kgly** [comment]
耀風您好，我將main.py貼至Google Cloud Functions，然而它需要1個進入點
但是我不清楚它的進入點是什麼?
_autosign?
一直執行還是不成功
感謝耀風。


![1](https://user-images.githubusercontent.com/4541492/166233374-369367de-7361-4c8f-8517-7de9a2166bba.png)

![2](https://user-images.githubusercontent.com/4541492/166233332-d96cd93b-4a4d-41cf-ae54-a879183fe528.png)


![3](https://user-images.githubusercontent.com/4541492/166240175-18a9a152-7e44-4175-bec4-9cfcf2a57620.png)

**Comment by kirbyloco** [comment]
我是不太清楚GCP的運作方式，
目前我的想法進入點是`_login`，
但可能要去修改一下程式碼，
像是帶入帳號密碼的部分。

**Comment by kirbyloco** [comment]
可能就會需要改成
```
def _login():
    data = {
        'uid': config['UID'],
        'passwd': config['PASSWD'],
        'vcode': '7045'
    }
    # 後面接原本的程式碼
```

**Comment by a5kgly** [comment]
耀風您好，依據網路上所查到的資訊。

一個Cloud Function，只會執行”一個”python程式內的function，你要把想執行的function name寫在「進入點」。


如果你有多個爬蟲function，應該要部署成多個Cloud Function，才符合設計的原理。


如此看來，符合google cloud functions的程式碼可能需要改很多。


感謝耀風
