### ISSUE TITLE
公會簽到

### ISSUE THREAD

**Issue by cjs835** [kirbyloco/gamer_autosignin#3]
main.py第65行中的regex會抓不到公會的ID，應該要改成`r'guild\.php\?gsn=(\d*)'`
https://github.com/kirbyloco/gamer_autosignin/blob/9c014183d9c5664f0a2613c4f5e76428be5de784/main.py#LL65C3-L65C3

**Comment by kirbyloco** [comment]
平常沒再用公會簽到也就沒注意到，晚點修正。
